sections:
  pages:
    create: default

  fields:
    type: fields
    fields:
      mainMenu:
        label: Hauptnavigation
        type: structure
        fields:
          mainMenu:
            type: pages
            label: Mainmenu item
            max: 1
          labelText:
            type: text
            label: Label
          hasSubmenu:
            type: toggle
            text: Include a submenu?
          subMenu:
            type: pages
            label: Submenu items
            when:
              hasSubmenu: true